# Shell variables
# Generated by 'wal'
wallpaper='/home/ayaka/Pictures/wallpaper/98461983_p0.png'

# Special
background='#060C11'
foreground='#abcac2'
cursor='#abcac2'

# Colors
color0='#060C11'
color1='#5F6054'
color2='#9D2B25'
color3='#AA554D'
color4='#DB635D'
color5='#6E8974'
color6='#B88977'
color7='#abcac2'
color8='#778d87'
color9='#5F6054'
color10='#9D2B25'
color11='#AA554D'
color12='#DB635D'
color13='#6E8974'
color14='#B88977'
color15='#abcac2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
