--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayaka/Pictures/wallpaper/98461983_p0.png"

-- Special
background="#060C11"
foreground="#abcac2"
cursor="#abcac2"

-- Colors
color0="#060C11"
color1="#5F6054"
color2="#9D2B25"
color3="#AA554D"
color4="#DB635D"
color5="#6E8974"
color6="#B88977"
color7="#abcac2"
color8="#778d87"
color9="#5F6054"
color10="#9D2B25"
color11="#AA554D"
color12="#DB635D"
color13="#6E8974"
color14="#B88977"
color15="#abcac2"
